language: php
php:
  - '7.1'
  - '7.2'
  - nightly
before_script: make
script: vendor/bin/phpunit --testsuite=OfflineTests

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: php-sdk-docs.cloudobjects.io
  on:
    php: '7.2'