language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_script: make
script: vendor/bin/phpunit --testsuite=OfflineTests

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: php-sdk-docs.cloudobjects.io
  on:
    php: '7.0'